# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.FloatField()),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('own', models.BooleanField(default=False)),
                ('annual', models.BooleanField(default=False)),
                ('annual_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.FloatField(blank=True, null=True)),
                ('story', models.FloatField(blank=True, null=True)),
                ('overall', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('comic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('mini_series_flag', models.BooleanField(default=False)),
                ('series_max', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('new52_flag', models.BooleanField(default=False)),
                ('marvel_now', models.BooleanField(default=False)),
                ('front_page', models.BooleanField(default=False)),
                ('alt_search_text', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set([('user', 'comic')]),
        ),
    ]
