# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_max_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
