# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dir_path', models.CharField(max_length=255)),
                ('folderPath', models.CharField(blank=True, max_length=255, null=True)),
                ('extension', models.CharField(blank=True, max_length=255, null=True)),
                ('error_flag', models.BooleanField(default=False)),
                ('review_flag', models.BooleanField(default=False)),
                ('comic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comic_issue', models.FloatField(blank=True, null=True)),
                ('comic_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('comic_year', models.CharField(blank=True, max_length=255, null=True)),
                ('comic_date', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_quallity', models.IntegerField(blank=True, null=True)),
                ('ads', models.BooleanField(default=True)),
                ('comic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Comic')),
            ],
        ),
        migrations.CreateModel(
            name='ComicReadAndOwn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own', models.NullBooleanField()),
                ('read', models.NullBooleanField()),
                ('trade', models.NullBooleanField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryComics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Comic')),
                ('comicFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicFiles.ComicFile')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Series')),
            ],
        ),
        migrations.CreateModel(
            name='RootFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('os_blob', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('status', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comicfile',
            name='rootFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comicFiles.RootFolder'),
        ),
        migrations.AlterUniqueTogether(
            name='primarycomics',
            unique_together=set([('series', 'comic', 'comicFile')]),
        ),
        migrations.AlterUniqueTogether(
            name='comicfile',
            unique_together=set([('name', 'dir_path')]),
        ),
    ]
