# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicfile',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
