# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicFiles', '0003_comicfile_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicfile',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
